export const BASE_URL = 'http://localhost:8080'
export const FACEBOOK_URL='https://facebook.com'
export const INSTAGRAM_URL='https://instagram.com'
export const TWITTER_URL='https://twitter.com'
export const YOUTUBE_URL='https://youtube.com'